name: saudi_cities
description: حزمة تحتوي على معلومات عن المدن في السعودية، بما في ذلك الملابس التقليدية، الطعام الشهير، والعادات والمعالم.
version: 0.0.3
repository: https://github.com/anasx3/saudi_cities.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/cities.json
