name: saudi_cities
description: A package that provides information about cities in Saudi Arabia, including traditional clothing, food, customs, and famous landmarks.
version: 0.0.4
repository: https://github.com/anasx3/saudi_cities.git

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/cities.json
